create table if not exists public.portraits (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  prompt text not null,
  image_url text not null,
  created_at timestamptz not null default now()
);

alter table public.portraits enable row level security;

revoke all on table public.portraits from anon, authenticated;
grant select on table public.portraits to anon, authenticated;
grant insert, update, delete on table public.portraits to authenticated;
grant usage, select on sequence public.portraits_id_seq to authenticated;

drop policy if exists "Public can read portraits" on public.portraits;
drop policy if exists "Public can create portraits" on public.portraits;
drop policy if exists "Public can update portraits" on public.portraits;
drop policy if exists "Public can delete portraits" on public.portraits;
drop policy if exists "Anyone can read portraits" on public.portraits;
drop policy if exists "Authenticated can create portraits" on public.portraits;
drop policy if exists "Authenticated can update portraits" on public.portraits;
drop policy if exists "Authenticated can delete portraits" on public.portraits;

create policy "Anyone can read portraits"
on public.portraits for select
to anon, authenticated
using (true);

create policy "Authenticated can create portraits"
on public.portraits for insert
to authenticated
with check ((select auth.uid()) is not null);

create policy "Authenticated can update portraits"
on public.portraits for update
to authenticated
using ((select auth.uid()) is not null)
with check ((select auth.uid()) is not null);

create policy "Authenticated can delete portraits"
on public.portraits for delete
to authenticated
using ((select auth.uid()) is not null);

-- 多分类正式数据源。portraits.category 仅保留旧数据兼容，不再由应用读写。
alter table public.portraits alter column category drop not null;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.portrait_categories (
  portrait_id bigint not null references public.portraits(id) on delete cascade,
  category_id bigint not null references public.categories(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (portrait_id, category_id)
);

alter table public.categories enable row level security;
alter table public.portrait_categories enable row level security;

revoke all on table public.categories from anon, authenticated;
grant select on table public.categories to anon, authenticated;
grant insert, delete on table public.categories to authenticated;
grant usage, select on sequence public.categories_id_seq to authenticated;

revoke all on table public.portrait_categories from anon, authenticated;
grant select on table public.portrait_categories to anon, authenticated;
grant insert, delete on table public.portrait_categories to authenticated;

drop policy if exists "Anyone can read categories" on public.categories;
drop policy if exists "Authenticated can create categories" on public.categories;
drop policy if exists "Authenticated can delete categories" on public.categories;

create policy "Anyone can read categories"
on public.categories for select
to anon, authenticated
using (true);

create policy "Authenticated can create categories"
on public.categories for insert
to authenticated
with check ((select auth.uid()) is not null);

create policy "Authenticated can delete categories"
on public.categories for delete
to authenticated
using ((select auth.uid()) is not null);

drop policy if exists "Anyone can read portrait categories" on public.portrait_categories;
drop policy if exists "Authenticated can create portrait categories" on public.portrait_categories;
drop policy if exists "Authenticated can delete portrait categories" on public.portrait_categories;

create policy "Anyone can read portrait categories"
on public.portrait_categories for select
to anon, authenticated
using (true);

create policy "Authenticated can create portrait categories"
on public.portrait_categories for insert
to authenticated
with check ((select auth.uid()) is not null);

create policy "Authenticated can delete portrait categories"
on public.portrait_categories for delete
to authenticated
using ((select auth.uid()) is not null);

-- 一次性迁移旧 portraits.category 值；可重复执行，不会生成重复分类或关联。
insert into public.categories (name)
select distinct trim(category)
from public.portraits
where category is not null and trim(category) <> ''
on conflict (name) do nothing;

insert into public.portrait_categories (portrait_id, category_id)
select portraits.id, categories.id
from public.portraits
join public.categories on categories.name = trim(portraits.category)
where portraits.category is not null and trim(portraits.category) <> ''
on conflict (portrait_id, category_id) do nothing;

-- 迁移验证：第一条应列出分类数量，第二条列出每个写真迁移后的分类。
select count(*) as category_count from public.categories;
select portraits.id, portraits.name, coalesce(string_agg(categories.name, ', ' order by categories.id), '未分类') as categories
from public.portraits
left join public.portrait_categories on portrait_categories.portrait_id = portraits.id
left join public.categories on categories.id = portrait_categories.category_id
group by portraits.id, portraits.name
order by portraits.id;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('portrait-images', 'portrait-images', true, 10485760, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can view portrait images" on storage.objects;
drop policy if exists "Public can upload portrait images" on storage.objects;
drop policy if exists "Public can update portrait images" on storage.objects;
drop policy if exists "Public can delete portrait images" on storage.objects;
drop policy if exists "Anyone can read portrait images" on storage.objects;
drop policy if exists "Authenticated can upload portrait images" on storage.objects;
drop policy if exists "Authenticated can update portrait images" on storage.objects;
drop policy if exists "Authenticated can delete portrait images" on storage.objects;

create policy "Anyone can read portrait images"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'portrait-images');

create policy "Authenticated can upload portrait images"
on storage.objects for insert
to authenticated
with check (bucket_id = 'portrait-images' and (select auth.uid()) is not null);

create policy "Authenticated can update portrait images"
on storage.objects for update
to authenticated
using (bucket_id = 'portrait-images' and (select auth.uid()) is not null)
with check (bucket_id = 'portrait-images' and (select auth.uid()) is not null);

create policy "Authenticated can delete portrait images"
on storage.objects for delete
to authenticated
using (bucket_id = 'portrait-images' and (select auth.uid()) is not null);
