create table if not exists public.portraits (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  prompt text not null,
  image_url text not null,
  created_at timestamptz not null default now()
);

alter table public.portraits enable row level security;

revoke all on table public.portraits from anon, authenticated;
grant select on table public.portraits to anon, authenticated;
grant insert, update, delete on table public.portraits to authenticated;
grant usage, select on sequence public.portraits_id_seq to authenticated;

drop policy if exists "Public can read portraits" on public.portraits;
drop policy if exists "Public can create portraits" on public.portraits;
drop policy if exists "Public can update portraits" on public.portraits;
drop policy if exists "Public can delete portraits" on public.portraits;
drop policy if exists "Anyone can read portraits" on public.portraits;
drop policy if exists "Authenticated can create portraits" on public.portraits;
drop policy if exists "Authenticated can update portraits" on public.portraits;
drop policy if exists "Authenticated can delete portraits" on public.portraits;

create policy "Anyone can read portraits"
on public.portraits for select
to anon, authenticated
using (true);

create policy "Authenticated can create portraits"
on public.portraits for insert
to authenticated
with check ((select auth.uid()) is not null);

create policy "Authenticated can update portraits"
on public.portraits for update
to authenticated
using ((select auth.uid()) is not null)
with check ((select auth.uid()) is not null);

create policy "Authenticated can delete portraits"
on public.portraits for delete
to authenticated
using ((select auth.uid()) is not null);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('portrait-images', 'portrait-images', true, 10485760, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can view portrait images" on storage.objects;
drop policy if exists "Public can upload portrait images" on storage.objects;
drop policy if exists "Public can update portrait images" on storage.objects;
drop policy if exists "Public can delete portrait images" on storage.objects;
drop policy if exists "Anyone can read portrait images" on storage.objects;
drop policy if exists "Authenticated can upload portrait images" on storage.objects;
drop policy if exists "Authenticated can update portrait images" on storage.objects;
drop policy if exists "Authenticated can delete portrait images" on storage.objects;

create policy "Anyone can read portrait images"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'portrait-images');

create policy "Authenticated can upload portrait images"
on storage.objects for insert
to authenticated
with check (bucket_id = 'portrait-images' and (select auth.uid()) is not null);

create policy "Authenticated can update portrait images"
on storage.objects for update
to authenticated
using (bucket_id = 'portrait-images' and (select auth.uid()) is not null)
with check (bucket_id = 'portrait-images' and (select auth.uid()) is not null);

create policy "Authenticated can delete portrait images"
on storage.objects for delete
to authenticated
using (bucket_id = 'portrait-images' and (select auth.uid()) is not null);
