-- ChatGPT 写真馆：单分类迁移为多分类
-- 可重复执行；不会重复创建分类或关联。

alter table public.portraits alter column category drop not null;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.portrait_categories (
  portrait_id bigint not null references public.portraits(id) on delete cascade,
  category_id bigint not null references public.categories(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (portrait_id, category_id)
);

alter table public.categories enable row level security;
alter table public.portrait_categories enable row level security;

revoke all on table public.categories from anon, authenticated;
grant select on table public.categories to anon, authenticated;
grant insert, delete on table public.categories to authenticated;
grant usage, select on sequence public.categories_id_seq to authenticated;

revoke all on table public.portrait_categories from anon, authenticated;
grant select on table public.portrait_categories to anon, authenticated;
grant insert, delete on table public.portrait_categories to authenticated;

drop policy if exists "Anyone can read categories" on public.categories;
drop policy if exists "Authenticated can create categories" on public.categories;
drop policy if exists "Authenticated can delete categories" on public.categories;

create policy "Anyone can read categories"
on public.categories for select
to anon, authenticated
using (true);

create policy "Authenticated can create categories"
on public.categories for insert
to authenticated
with check ((select auth.uid()) is not null);

create policy "Authenticated can delete categories"
on public.categories for delete
to authenticated
using ((select auth.uid()) is not null);

drop policy if exists "Anyone can read portrait categories" on public.portrait_categories;
drop policy if exists "Authenticated can create portrait categories" on public.portrait_categories;
drop policy if exists "Authenticated can delete portrait categories" on public.portrait_categories;

create policy "Anyone can read portrait categories"
on public.portrait_categories for select
to anon, authenticated
using (true);

create policy "Authenticated can create portrait categories"
on public.portrait_categories for insert
to authenticated
with check ((select auth.uid()) is not null);

create policy "Authenticated can delete portrait categories"
on public.portrait_categories for delete
to authenticated
using ((select auth.uid()) is not null);

insert into public.categories (name)
select distinct trim(category)
from public.portraits
where category is not null and trim(category) <> ''
on conflict (name) do nothing;

insert into public.portrait_categories (portrait_id, category_id)
select portraits.id, categories.id
from public.portraits
join public.categories on categories.name = trim(portraits.category)
where portraits.category is not null and trim(portraits.category) <> ''
on conflict (portrait_id, category_id) do nothing;

-- 验证迁移结果
select count(*) as category_count from public.categories;

select
  portraits.id,
  portraits.name,
  coalesce(string_agg(categories.name, ', ' order by categories.id), '未分类') as categories
from public.portraits
left join public.portrait_categories on portrait_categories.portrait_id = portraits.id
left join public.categories on categories.id = portrait_categories.category_id
group by portraits.id, portraits.name
order by portraits.id;
